### ISSUE TITLE
what does the option :target do in etl/apply-pipeline

### ISSUE THREAD

**Issue by hoebat** [cnuernber/ames-house-prices#1]
In the [jupyter notebook](https://nbviewer.jupyter.org/github/cnuernber/ames-house-prices/blob/acb961538e9b1cbbef8fb1733ecdd4b0012ffd89/ames-housing-prices-clojure.ipynb) on Line 16, there is a call:

```
(def skew-fix-result (etl/apply-pipeline missing-fixed 
                                         fix-all-skew 
                                         {:target "SalePrice"}))
```

what does this do to the dataset?

**Comment by cnuernber** [comment]
```clojure
(def fix-all-skew
  '[[m= [and
         [numeric?]
         [not "SalePrice"]
         [> (abs (skew (col))) 0.5]]
     (log1p (col))]])
```

Basically for all the columns that are numeric and not sale price which is the target column (the column we wish to predict) and for whom the absolute value of skew is greater than 0.5, transform them elementwise by log1p.   This is from the original article and there is some discussion about how effective it was or was not in the notebook.  

The apply pipeline operation takes a dataset, applies a pipeline, and returns a map of:
```clojure
{:dataset :pipeline :options}
````
The dataset is the new dataset, the pipeline is the pipeline to run at inference time, and options is a set of parameters about the dataset (such as what numeric values stand for what string values).

The way the pipeline changes from training and inference is that any pipeline operator implements basically two functions:
```clojure
(get-context)
(perform-etl)
```

They are strung together like this:

```clojure
;; Training
(let [context (get-context dataset)]
  (perform-etl dataset context))

;;Inference
(perform-etl dataset context)

```

In this way we strive to ensure that code that generates dataset-specific context for applying an operation does not run during inference time when that information should not be generated.


So, putting it all together we have an attempted specific fix to the problem of dataset skew, applied conditionally to the columns that have high skew in absolute terms.  At training time, the set of columns is generated; this is the context.

But at inference time, we use the set of columns discovered during the training process so the entire pipeline is fixed.

**Comment by hoebat** [comment]
How does `:target` affect the apply-pipeline call? This entry is not present in any of the other calls to etl/apply-pipeline.

**Comment by cnuernber** [comment]
Setting a column or set of columns as the target sets up metadata that marks them as the inference target for later train/predict runs.  This avoids having to re-specify this later after dataset processing.

**Comment by hoebat** [comment]
sweet. got it.
